### ISSUE TITLE
Add infos for dummies to readme

### ISSUE THREAD

**Issue by dnlm** [adn77/alexa-cookie-cli#1]
Hey, 2 things you could consider to include in the readme:

1. Hint to start the exe from a command line. I just opened it from explorer and the window closed automatically after fetching the token. (Now that I write this, maybe you could add sth like "press any key to continue" after the token has been fetched so the window doesn't close?)
2. Link to the latest binary download page. I know the Link is on the right sidebar, but most projects include the link in the readme and I think it's a good idea so people new to github aren't lost (TBH I looked in the text first and was lost for a few seconds 😝).

**Comment by Apollon77** [comment]
Why you are not providing a PR for the Readme?

Simple open the README.md, click the pencil top right and edit the file, when done scroll down and propose your change and create a PR ... very easy way in web

**Comment by dnlm** [comment]
Will do so, sorry ;)

**Comment by dnlm** [comment]
I created the PR and noticed that you mentioned the command line issue with the word attention in bold capital letters before the hint. Guess I'm just awake for too long, sorry for bothering you. I created a PR with the link to the latest release anyway. Thanks again for creating this and solving an issue that was really bothering me for months :)

**Comment by adn77** [comment]
There's actually a rather big hint already to make sure the app is started from the command line...
Waiting for a key press is the smarter solution. I'll check what I can do...

**Comment by adn77** [comment]
I added the `while(true)` loop unless the *--quiet* option is used.

Although not very elegant, it seems to do the job... I'm mostly clueless when it comes to this type of JS programming - don't tell anybody :D

**Comment by Apollon77** [comment]
I would not do a while true because it "burns" CPU just for nothing, maybe ok to say "I now wait 60s before I quit" or something like this? Then a normal setTimeout would do the job better
