### ISSUE TITLE
error when used in AU

### ISSUE THREAD

**Issue by skarotech** [adn77/alexa-cookie-cli#4]
Hi, I have tried to use this for AU (alexa.amazon.com.au/amazon.com.au) with the following, but always get an error

SyntaxError: Unexpected end of JSON input / null

It look like it always heads to alexa.amazon.com whereas here its alexa.amazon.com.au

node cli.js -H 192.168.1.128 -a en-AU -L en-AU -q -p amazon.com.au -b amazon.com -V debug
[HPM] Proxy created: !/cookie-success  -> https://alexa.amazon.com
[HPM] Proxy rewrite rule created: "^/www.amazon.com" ~> ""
[HPM] Proxy rewrite rule created: "^/alexa.amazon.com" ~> ""
[HPM] Subscribed to http-proxy events: [ 'error', 'proxyReq', 'proxyRes', 'close' ]
Error: You can try to get the cookie manually by opening http://192.168.1.128:8080/ with your browser. / null
[HPM] Router new target: https://alexa.amazon.com -> "https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.client_id=device%3A463430453135354645413931423937363033303132414234383646373842313723413249564c5635564d32573831&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.oa2.response_type=code&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&openid.oa2.code_challenge_method=S256&openid.oa2.code_challenge=Q3QK6K0TXzI2198oJ3WZd8rUWjsdNuGWNFYVGNNQab8&language=en-AU"
[HPM] GET / => https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.client_id=device%3A463430453135354645413931423937363033303132414234383646373842313723413249564c5635564d32573831&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.oa2.response_type=code&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&openid.oa2.code_challenge_method=S256&openid.oa2.code_challenge=Q3QK6K0TXzI2198oJ3WZd8rUWjsdNuGWNFYVGNNQab8&language=en-AU
[HPM] Router new target: https://alexa.amazon.com -> "https://www.amazon.com"
[HPM] GET /ap/uedata?ld&v=0.221671.0&id=ZXZJFWXX5WZ24J0GFGMG&sw=2560&sh=1440&vw=1247&vh=1231&m=1&sc=ZXZJFWXX5WZ24J0GFGMG&ue=2&bb=20&cf=27&be=28&fp=26&fcp=26&pc=64&tc=-1365&na_=-1365&ul_=-1653711630521&_ul=-1653711630521&rd_=-1653711630521&_rd=-1653711630521&fe_=-1358&lk_=-1358&_lk=-1358&co_=-1358&_co=-1358&sc_=-1653711630521&rq_=-1356&rs_=-15&_rs=-9&dl_=-8&di_=42&de_=42&_de=42&_dc=64&ld_=64&_ld=-1653711630521&ntd=-1&ty=0&rc=0&hob=1&hoe=2&ld=65&t=1653711630586&ctb=1&rt=cf:16-8-3-1-3-15-1__ld:17-9-3-1-4-16-1&csmtags=aui|aui:aui_build_date:3.21.8-2022-03-24|fls-na-amazon-com|adblk_no&viz=visible:2&pty=AuthenticationPortal&spty=MobileSignInApplication&pti=undefined&tid=7TEH3S5QMRVKQRG9EP88&aftb=1 => https://www.amazon.com
[HPM] Router new target: https://alexa.amazon.com -> "https://www.amazon.com"
[HPM] GET /ap/uedata?at&v=0.221671.0&id=ZXZJFWXX5WZ24J0GFGMG&ctb=1&m=1&sc=ZXZJFWXX5WZ24J0GFGMG&pc=11339&at=11339&t=1653711641860&csmtags=csm-feature-touch-enabled:false&pty=AuthenticationPortal&spty=MobileSignInApplication&pti=undefined&tid=7TEH3S5QMRVKQRG9EP88&aftb=1 => https://www.amazon.com
[HPM] Router new target: https://alexa.amazon.com -> "https://www.amazon.com"
[HPM] GET /ap/uedata?at&v=0.221671.0&id=ZXZJFWXX5WZ24J0GFGMG&ctb=1&m=1&sc=ZXZJFWXX5WZ24J0GFGMG&pc=11346&at=11346&t=1653711641867&pty=AuthenticationPortal&spty=MobileSignInApplication&pti=undefined&tid=7TEH3S5QMRVKQRG9EP88&aftb=1&ui=2 => https://www.amazon.com
[HPM] Router new target: https://alexa.amazon.com -> "https://www.amazon.com"
[HPM] Rewriting path from "/www.amazon.com/ap/signin" to "/ap/signin"
[HPM] POST /www.amazon.com/ap/signin ≈> https://www.amazon.com
SyntaxError: Unexpected end of JSON input / null

**Comment by Apollon77** [comment]
Please show the used options for this call

**Comment by skarotech** [comment]
Command line is

node cli.js -H 192.168.1.128 -a en-AU -L en-AU -q -p amazon.com.au -b amazon.com -V debug

**Comment by adn77** [comment]
First things first, I didn't create that cool proxy - all I did was providing a wrapper for it ;) All credits go to @Apollon77.

From what I can see here: https://github.com/Apollon77/alexa-cookie/blob/master/lib/proxy.js only the `baseAmazonPage` gets used (which should be amazon.com as per the example.js, and which you already set correctly).

Unfortunately the `-V` option only turns on debugging in the proxy itself. Try using `-l console.debug`.

I guess, you already tried using _amazon.com.au_ as the base domain?

From what I can read here https://github.com/Apollon77/alexa-cookie/issues/48 , adjusting the base domain should not be necessary.
If the problem persists, could you please open an issue with the original repo?

**Comment by Apollon77** [comment]
@adn77 can you not set "opt.logger" to console.log when loglevekl is debug or such - or simply in general?

@skarotech can you try add to the cli.js before https://github.com/adn77/alexa-cookie-cli/blob/master/cli.js#L19 to add a line with

´opt.logger = console.log;`

and post out put then please?

**Comment by Apollon77** [comment]
Please also try to set "-b" with amazon.com.au ... I think region wise this could be like with amazon.co.jp and -b the same

**Comment by adn77** [comment]
@Apollon77 thanks for helping out :)

The default logger is set to `console.error` unless specified otherwise. I was hoping this is StdError.

From what I saw in your code this can also be set to `console.debug`?!

**Comment by Apollon77** [comment]
Aahh I missed that small detail maybe use console.log? I would have exected more loglines then the one in the first post
